Caprice Reloaded :  * Don't compile glfuncs things if not using OpenGL  * Remove SDL from png saing code (should probably be done on gui side actually)  * use C standard types instead of sdl ones  * Link the exe in the proper oder (static libs first) or else we get undefined references
StSound:
 * Update libtool (the older one was failing in some cases)

We are near a running Caprice, only an undefined reference to WinMain@16 is left. Investigating why...